previewsEnabled: true
services:
  - type: web
    name: tracker
    env: node
    repo: https://github.com/shwld/typescript-agile-boilerplate
    region: oregon
    # plan: starter # consoleで決めたいので消す
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    # numInstances: 1
    healthCheckPath: /
    branch: main
    autoDeploy: false
