name: Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    # env:
    #   TZ: Asia/Tokyo

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'
      - name: install, build
        run: yarn --frozen-lockfile
      - name: run type check
        run: yarn tscheck
      - name: run lint
        run: yarn lint
      - name: run prettier
        run: yarn prettier:check
